server:
  port: 8099

app:
  settings:
    sample.enabled: true
    taskCount: 1
  cadence:
    domain: rsa_main_domain
    host: localhost
    port: 7933
    pooler:
      activity:
        pollThreadCount: 50
      workflow:
        pollThreadCount: 50
        sticky:
          pollThreadCount: 50

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web.exposure.include: '*'
  metrics.export.prometheus.enabled: true

logging:
  level:
    ru.stas: DEBUG
    com.uber: DEBUG
    org.springframework: ERROR
    ROOT: ERROR
