version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
